### ISSUE TITLE
(ignore) about Circuit-ORAM res->tree

### ISSUE THREAD

**Issue by weikengchen** [samee/sqrtOram#2]
Please ignore this issue. It is due to my misunderstanding of the code.

```
res->index_size = logN;
res->position_label_size = logN;
res->N = 1 << logN;      //here
```

```
	res-> tree = calloc_obliv(sizeof(Block**), res->N /* here*/);
	res-> stash = calloc_obliv(sizeof(Block*), res->stash_size);
	for(int i = 0; i < res->N /* here*/; ++i) {
		res->tree[i] = calloc_obliv(sizeof(Block*), res->bucket_size);
		for(int j = 0; j < res->bucket_size; ++j)
			res->tree[i][j] = block_initialize(res->cpy);
```

I misunderstood the structure of `res->tree`, the index of which is for every node, not for every layer.

**Comment by weikengchen** [comment]
And a big thanks to Samee and other people on Obliv-C. 
I use your Obliv-C for my first paper. 

Easy to learn! Good platform!

**Comment by weikengchen** [comment]
The code I refer to is in this file: https://github.com/samee/sqrtOram/blob/master/oram/nonrecursive_oram.oc

**Comment by weikengchen** [comment]
@jackdoerner  any idea?

**Comment by weikengchen** [comment]
my bad. 

Just find that this is different from the path[i][j].

Sorry!

**Comment by evansuva** [comment]
Thanks @weikengchen - good to hear you are finding it useful!
 
We like to keep links to projects and papers using Obliv-C on the oblivc.org website, so let me know when there is something you'd like us to add a link to there.

**Comment by weikengchen** [comment]
Thanks! Will do.
