### ISSUE TITLE
make failes at Ubuntu 18.10 (and some other platforms)

### ISSUE THREAD

**Issue by drn98** [samee/sqrtOram#5]
I have tried to make sqrtOram but processing the makefile failed with the following error message:

```
/home/myusername/obliv-c/bin/oblivcc -c -O3 oram/sqrtoram.oc -I oram -I util -I /home/myusername/obliv-c/src/ext/oblivc -o build/oram/sqrtoram.oc
/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h[21:12-28] : syntax error
Parsing errorFatal error: exception Frontc.ParseError("Parse error")
make: *** [Makefile:111: build/oram/sqrtoram.oo] Error 2
```

I successfully installed obliv-c previously and followed the instructions for Ubuntu in the readme.md-File. Any information on how to build sqrtOram would be helpful as it is a required dependency for another program I want to compile.

**Comment by samee** [comment]
Verified. Something must have changed in the standard library to break this. The short-term workaround will be to have SqrtOram never include math.h from an .oc file, but link to a separate .c file. In the long term, we should probably learn how to deal with float and complex floats that automatically get included. I will look into it.

**Comment by drn98** [comment]
Alright, thank you very much. Can you please explain the short-term workaround further? I want to compile the KMP program mentioned on the obliv-c page and also other programs, and sqrtOram is a dependency.

**Comment by samee** [comment]
Actually, there might be an easier way. If we could just avoid linking in math.h, our problem would be solved. I am guessing `oram/sqrtoram.oc` includes it just to call `ceil(sqrt(...))`. As long as you can implement it using integer-only arithmetic (e.g. by binary-searching over `x*x`), it should allow us to remove `#include <math.h>`. Is that something you can do?

**Comment by drn98** [comment]
That task should be trivial, I guess. I'll have a look and will report again. Thanks.

**Comment by drn98** [comment]
```
#define MAX_ITER 12
// Adjust in favour of performance or accuracy

double sqrt(double a)
{
    double x, y;
    register unsigned int iter;

    x = a;
    y = 1;

    for (iter = 0; iter < MAX_ITER; iter++)
    {
        x = (x + y)/2;
        y = a/x;
    }

    return a;
}
```

Here's my lm-free sqrt implementation (Heron). Now working on ceil likewise.

**Comment by drn98** [comment]
```
// unused but potentially helpful

double ipow_10(int x)
{
    double y = 10.0;

    register int i;

    if (x > 1)
    {
	for (i = 1; i < x; i++)
	    y = y * 10;
    }
    else if (x == 1)
    {
        y = y;
    }
    else if (x == 0)
    {
	y = 1.0;
    }
    else if (x < 0)
    {
	for (i = 1; i > x; i--)
	    y = y/10.0;
    }

    return y;
}

double ceil(double x)
{
	double y = 0;

	if (x > 0)
	{
		while (x > 1)
		{
			x -= 1.0;
			y += 1.0;
		}
	}
    if (x == +0 || x == -0)
    {
        return 0.0;
    }
    if (x < 0)
    {
        while (x < 0)
        {
            x -= 1.0;
            y += 1.0;
        }
    }
	return x;
}
```

Here is my (painfully inefficient, I'll leave this to the compiler, first) ceil implementation which is trivially subtracting 1 until the value that's left is lower than 1. The function above was my attempt to use an improved search with powers of 10 (which required me to replace the pow-function), which I did not finished.

**Please remember that we're dealing with cryptography** and as trivial as my contribution might appear, I warn about any possible misuse. Cryptographic implementations requires more caution than I could give for this quick workaround.

**Comment by samee** [comment]
Sorry about the pain. Try this instead:

```C
size_t ceilsqrt(size_t x) {
  size_t lo=0,hi=(((size_t)1)<<4*sizeof(size_t))-1,mid;
  while(lo<hi) {
    mid=(lo+hi)/2;
    if(mid*mid>=x) hi=mid;
    else lo=mid+1;
  }
  return lo;
}
```

**Comment by drn98** [comment]
Doesn't this assume that size_t's maximum value is greater than the actual occurring value of the double var (which is possible to be a wrong assumption)? This was the reason I decided against casting.

Anyway, I just included my two functions and uncommented #include <math.h> and I successfully build liboram.a which I never managed to do before. Thank you for pointing out the cause of the flaw.

**Comment by samee** [comment]
Glad it worked out.

The code in question (https://github.com/samee/sqrtOram/blob/master/oram/sqrtoram.oc#L286) needlessly goes from `size_t -> double -> int`, invoking inexact floating point operations. We shouldn't need to use `double` at all. This code at least consistently uses `size_t`.

**Comment by drn98** [comment]
I just tried to compile kmp-mpc and it failed (segmentation fault), and I'm not sure if my modification is the reason or it just would've happened anyway. Do you have any idea how I can find out?

**Comment by drn98** [comment]
> Circuit ORAM had a bug in memory management when data size is large enough for recursion. (#1 )

Since there is a seemingly infinite calling of sqrtPosMapRecurNew() and ocSqrtOramNewAux() again and again, I suspect this is the recursion that is mentioned in the other, quoted issue?

**Comment by thiline** [comment]
> Glad it worked out.
> 
> The code in question (https://github.com/samee/sqrtOram/blob/master/oram/sqrtoram.oc#L286) needlessly goes from `size_t -> double -> int`, invoking inexact floating point operations. We shouldn't need to use `double` at all. This code at least consistently uses `size_t`.

**Comment by thiline** [comment]
Is there any solution for this issue ?

**Comment by samee** [comment]
I hadn't realized this thread still has outstanding issues. @thiline what is the current problem you are having? The original problem reported here was apparently solved a few comments up:

> Anyway, I just included my two functions and uncommented #include <math.h> and I successfully build liboram.a which I never managed to do before. Thank you for pointing out the cause of the flaw.

I @drn98 can probably give you more details if needed.

**Comment by thiline** [comment]
> Doesn't this assume that size_t's maximum value is greater than the actual occurring value of the double var (which is possible to be a wrong assumption)? This was the reason I decided against casting.
> 
> Anyway, I just included my two functions and uncommented #include <math.h> and I successfully build liboram.a which I never managed to do before. Thank you for pointing out the cause of the flaw.

@drn98 Could you please explain your solution a bit more ? Thank you.

**Comment by thiline** [comment]
@samee followed the instructions and I believe that I built this successfully. Thank you !

**Comment by samee** [comment]
Glad it worked. Happy new year!
